name: qsymm-latest
channels:
    - conda-forge
dependencies:
    - python=3.11
    - numpy
    - scipy
    - sympy
    - tinyarray
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
