name: qsymm-minimal
channels:
    - conda-forge
dependencies:
    - python=3.9
    - numpy=1.19
    - scipy=1.7
    - sympy=1.9
    - tinyarray=1.2.4
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
