channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=2.0
  - scipy>=1.13
  - sympy>=1.13
  - tinyarray>=1.2.4
  - sphinx>=8.2
  - jupyter-sphinx
  - sphinx_rtd_theme
  - m2r2
  - lxml-html-clean
